### ISSUE TITLE
feature request: pls add overlays from: https://waymarkedtrails.org/

### ISSUE THREAD

**Issue by telemaxx** [opoto/wtracks#13]
These overlays are great:

https://cycling.waymarkedtrails.org/
https://mtb.waymarkedtrails.org/
https://hiking.waymarkedtrails.org/

**Comment by opoto** [comment]
Added in https://github.com/opoto/wtracks/commit/00ff9789b5c4709c782e982ecef8f1d4fb5f1c3f
Ultimately there should be an overlay editor, just as there is a map editor, so that anyone can add his/her preferred overlays. Any pull request for this is welcome!
Thanks

**Comment by telemaxx** [comment]
this was fast. 
looks great now.
this overlays are so great. often i don't need a gpx to follow,  just these kind of maps.

 you're route planer is fantastic,  i searched a replacement for gpsies and found youre wtracks. thanks. 

you're are right,  an overlay editor would be a good improvement...
