### ISSUE TITLE
Add ability to edit/move waypoints

### ISSUE THREAD

**Issue by YodaDaCoda** [opoto/wtracks#14]
I have a gpx track that's just a series of waypoints. I'd like to be able to move some of them to adjust the position and their order in the output file.

**Comment by opoto** [comment]
Hi
Just click the edition tool on the left of the map.
Check the documentation at https://opoto.github.io/wtracks/doc/#features
Regards
--
Olivier

**Comment by julie777** [comment]
I believe you mean "edit tool" instead of "edition tool".
