### ISSUE TITLE
Feature Request: show waypoint name

### ISSUE THREAD

**Issue by telemaxx** [opoto/wtracks#15]
currently i can nicely edit the position of waypoints. great. 

it would be nice to optionally display the waypoint names.

**Comment by opoto** [comment]
Hello
Waypoint title is already displayed as a tooltip when moving the mouse over the waypoint. Do you mean displaying the title aside the waypoint icon, even when there is no mouse over?

**Comment by telemaxx** [comment]
just tried on my laptop. mouse over is working.
but how to show on my mobile? no mouse, no mouse over ;-)
a text below the icon would be cool.

Thanks.

**Comment by opoto** [comment]
Feature has been added, please check the Settings / Display options / Always display waypoint labels.
Hope this answers your request.

**Comment by telemaxx** [comment]
perfect.  thank you very much.
