### ISSUE TITLE
Documentation uses edition instead of edit

### ISSUE THREAD

**Issue by julie777** [opoto/wtracks#16]
All through the documentation the word edition is used which doesn't make sense to me as a native English speaker. I believe you should be using the various form of the verb edit.
edit - make a change
editing - in the process of making changes
edit tools - tools for making changes

(Thanks for sharing a great project.)

**Comment by opoto** [comment]
Thanks for the notice. I'm afraid my English still requires some improvement...
I updated documentation in d81b140 according to your indications, do not hesitate to tell me if further changes are needed.

**Comment by julie777** [comment]
Your English isn’t bad. I can’t imagine working in a second language. I am impressed.
