### ISSUE TITLE
Feature request: save tracks on server

### ISSUE THREAD

**Issue by brosky** [opoto/wtracks#17]
Hi, 

A nice feature is that the user is able to save the files on the filesystem where the scripts are and other users/sessions be able to see  and use them. 
Also , adding a multi-user feature will make this app more popular. 👍

**Comment by opoto** [comment]
Hi
As you may have noticed, WTracks is "serverless", it is just html+js running in your browser, so no server to save to.  Cloud storage of files is another type of app, and I would like to avoid reinventing it. This is why WTracks is integrated with a popular cloud storage, namely Dropbox, where you can save your files and share them. The "share" option also offers an alternative storage mechanism, where tracks are uploaded to anonymous cloud storage, and you get a url you can reuse. Note that with tempfile service the track is deleted after one month.
Possibly I may consider adding other storage options, as long as they are offered by an external service.
