### ISSUE TITLE
New WMS map cannot be used 

### ISSUE THREAD

**Issue by cmoulliard** [opoto/wtracks#18]
# Issue

I added a new WMS map using the following WMS url : WMS: https://cartoweb.wms.ngi.be/service?request=GetCapabilities&service=WMS&version=1.3.0 (as documented [here](https://www.ngi.be/website/fr/offre/geodonnees-numeriques/cartoweb-be-2/))

![Screenshot 2021-05-27 at 09 07 31](https://user-images.githubusercontent.com/463790/119781321-2ac31a80-becb-11eb-867f-6812d005a273.png)

but I cannot use it

![Screenshot 2021-05-27 at 09 07 17](https://user-images.githubusercontent.com/463790/119781337-2f87ce80-becb-11eb-8f36-434bd0e35baa.png)

Can you tell me what it is wrong please ?

That fails too using the WMTS url: https://cartoweb.wmts.ngi.be/1.0.0/WMTSCapabilities.xml

![Screenshot 2021-05-27 at 16 25 05](https://user-images.githubusercontent.com/463790/119843874-3b45b600-bf08-11eb-8667-8bfaf0bb2529.png)

**Question**: What should be the values for `From` to `Zoom` ?

**Comment by cmoulliard** [comment]
Something else. If I select as layer `overlay` and not `topo`, then we get a `CORS` error

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://cartoweb.wms.ngi.be/service?request=GetCapabilities&service=WMS&version=1.3.0&service=WMS&request=GetMap&layers=overlay&styles=default&format=image%2Fpng&transparent=false&version=1.1.1&width=256&height=256&srs=EPSG%3A3395&bbox=513045.33385010314,6453279.054064782,513351.0819632438,6453583.961270058 with MIME type application/xml. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Comment by opoto** [comment]
You can use following settings:
![image](https://user-images.githubusercontent.com/1472722/119851028-5e736400-bf0e-11eb-9d60-3b9cc4082645.png)

To import it click on below link:

https://opoto.github.io/wtracks/maps.html?import=eyJCRSBDYXJ0b1dlYiI6eyJvcHRpb25zIjp7Im1pblpvb20iOiI1IiwibWF4Wm9vbSI6IjIwIiwibGF5ZXJzIjoidG9wbyIsImNycyI6IkVQU0c6NDMyNiIsInN0eWxlcyI6ImRlZmF1bHQiLCJmb3JtYXQiOiJpbWFnZS9wbmciLCJhdHRyaWJ1dGlvbiI6ImNhcnRvd2ViLmJlIn0sInVybCI6Imh0dHBzOi8vY2FydG93ZWIud21zLm5naS5iZS9zZXJ2aWNlIiwidHlwZSI6IndtcyIsIm5hbWUiOiJDYXJ0b1dlYiBCRSJ9fQ==

**Comment by cmoulliard** [comment]
I will close the issue as the problem is fixed. If I experiment again the CORS problem, then I will describe it in another ticket. WDYT ? @opoto

**Comment by opoto** [comment]
good for me, thanks
