### ISSUE TITLE
How to avoid to display this annoying hashed line when we edit ?

### ISSUE THREAD

**Issue by cmoulliard** [opoto/wtracks#19]
## Issue

How to avoid to have this annoying hashed line when we edit a trace ?

![Screenshot 2021-05-27 at 09 16 38](https://user-images.githubusercontent.com/463790/119782387-6dd1bd80-becc-11eb-985d-661432f62a77.png)

## Info

Browser used: Google Chrome - Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by opoto** [comment]
Hello

Today there is no way to get rid of this dashed line in edit mode. It helps to pre-visualize the segment extension you will create by clicking on the map (which creates a new track point). Of course when you quit edit mode this line is not displayed anymore.

Why do you think this line should not be displayed?
Would you like to have it in some cases, but not others?

**Comment by cmoulliard** [comment]
> Would you like to have it in some cases, but not others?

I dont want to see it by example when we would like to edit a trace which already exists from one of the points 

![Screenshot 2021-05-27 at 17 21 20](https://user-images.githubusercontent.com/463790/119853267-55839200-bf10-11eb-9539-0774906555b7.png)

**Comment by opoto** [comment]
You can now uncheck "Show forward line guide" to hide this guide:
![image](https://user-images.githubusercontent.com/1472722/120242636-aa533f80-c265-11eb-87d2-1255c9fb0968.png)
