### ISSUE TITLE
feature: swisstopo

### ISSUE THREAD

**Issue by eddy-geek** [opoto/wtracks#22]
> From March 1, 2021, the Federal Office of Topography swisstopo will make its official digital data and services available online free of charge as Open Government Data (OGD). As of now, no registration is required to download the data or use the geoservices WMS, WMTS and all services of the RESTful API.

It seems WTracks is not famous yet in Switzerland, let's change it :)

* Official [documentation](https://www.geo.admin.ch/en/home.detail.news.html/geo-internet/news2021/news20210301.html)
* sample Leaflet implementation: https://www.openslopemap.org/leaflet/js/map.js
* sample OpenLayers implementation (topo & slope): c2c [map-layers.js](https://github.com/c2corg/c2c_ui/blob/master/src/components/map/map-layers.js)

**Comment by opoto** [comment]
I actually already configured these maps locally, but did not include them in the pre-configured maps:

- pixelkarte-farbe: https://opoto.github.io/wtracks/maps.html?import=eyJDSCBzY2FsYWJsZSI6eyJvcHRpb25zIjp7Im1pblpvb20iOiI1IiwibWF4Wm9vbSI6IjIwIiwibGF5ZXJzIjoiY2guc3dpc3N0b3BvLnBpeGVsa2FydGUtZmFyYmUiLCJjcnMiOiJFUFNHOjQzMjYiLCJzdHlsZXMiOiIiLCJmb3JtYXQiOiJpbWFnZS9wbmciLCJhdHRyaWJ1dGlvbiI6IiJ9LCJ1cmwiOiJodHRwczovL3dtcy5nZW8uYWRtaW4uY2gvIiwidHlwZSI6IndtcyIsIm5hbWUiOiJDSCBzY2FsYWJsZSJ9fQ==
- pixelkarte-farbe-pk25: https://opoto.github.io/wtracks/maps.html?import=eyJDSCAyNWUiOnsib3B0aW9ucyI6eyJtaW5ab29tIjoiNSIsIm1heFpvb20iOiIyMCIsImxheWVycyI6ImNoLnN3aXNzdG9wby5waXhlbGthcnRlLWZhcmJlLXBrMjUubm9zY2FsZSIsImNycyI6IkVQU0c6NDMyNiIsInN0eWxlcyI6IiIsImZvcm1hdCI6ImltYWdlL3BuZyIsImF0dHJpYnV0aW9uIjoiIn0sInVybCI6Imh0dHBzOi8vd21zLmdlby5hZG1pbi5jaC8iLCJ0eXBlIjoid21zIiwibmFtZSI6IkNIIDI1ZSJ9fQ==
- images-swissimage: https://opoto.github.io/wtracks/maps.html?import=eyJDSCBzYXRlbGxpdGVzIjp7Im9wdGlvbnMiOnsibWluWm9vbSI6IjUiLCJtYXhab29tIjoiMjAiLCJsYXllcnMiOiJjaC5zd2lzc3RvcG8uaW1hZ2VzLXN3aXNzaW1hZ2UiLCJjcnMiOiJFUFNHOjQzMjYiLCJzdHlsZXMiOiIiLCJmb3JtYXQiOiJpbWFnZS9wbmciLCJhdHRyaWJ1dGlvbiI6IiJ9LCJ1cmwiOiJodHRwczovL3dtcy5nZW8uYWRtaW4uY2gvIiwidHlwZSI6IndtcyIsIm5hbWUiOiJDSCBzYXRlbGxpdGVzIn19

**Comment by opoto** [comment]
Added in 32884fd
