### ISSUE TITLE
feature request: sort segments

### ISSUE THREAD

**Issue by wstoettinger** [opoto/wtracks#24]
Hi,
your tool is very useful for editing tracks, however, i have the problem that the segments of the tracks I need to edit are not in the correct order, so once I click "join segments" the tracks are messed up. 
It would be great to have a function to sort the segments before joining.

thanks!

**Comment by opoto** [comment]
Hi
Yes, I agree this would be useful. A pre-requisite would be to identify tracks, by color, name, or whatever. Do you have any suggestion?
Thanks

**Comment by wstoettinger** [comment]
Hi,
gpx.studio numbers the segments and uses colors, but the sorting functionality there is useless when there are more than 3-4 segments because you can't properly move them. It would definitely be great to have a list on the side where the segment is highlighted on the map as well when it is selected in the list. Then it's easy to check if the order is correct and reorder them with drag&drop.

Thanks

**Comment by opoto** [comment]
Ok, thanks for your suggestions.
I have no clue when I will have time to work on this, and definitely not in the coming weeks. 
Do not hesitate to propose a PR!

**Comment by opoto** [comment]
Implemented in cbd47d0
The segment editor is in the toolbox on the left of the map (not very visible, there might be a better way to present it), instead of the previous "delete segment" button

**Comment by opoto** [comment]
I eventually moved the segments editor to the "Tools" menu
