### ISSUE TITLE
Map import fails if data has `+`

### ISSUE THREAD

**Issue by eddy-geek** [opoto/wtracks#29]
Example:

```json
{"Sorbetto":{"options":{"minZoom":"12","maxZoom":"16","attribution":"&copy; CC BY-NC-SA 3.0 IT <a href='https://tartamillo.wordpress.com'>Maki</a>"},"url":"//www.montagne.top/maki/Sorbetto/{z}/{x}/{y}.jpg","type":"base","overlay":false}}
```

base 64 URL: 
https://opoto.github.io/wtracks/maps.html?import=eyJTb3JiZXR0byI6eyJvcHRpb25zIjp7Im1pblpvb20iOiIxMiIsIm1heFpvb20iOiIxNiIsImF0dHJpYnV0aW9uIjoiJmNvcHk7IENDIEJZLU5DLVNBIDMuMCBJVCA8YSBocmVmPSdodHRwczovL3RhcnRhbWlsbG8ud29yZHByZXNzLmNvbSc+TWFraTwvYT4ifSwidXJsIjoiLy93d3cubW9udGFnbmUudG9wL21ha2kvU29yYmV0dG8ve3p9L3t4fS97eX0uanBnIiwidHlwZSI6ImJhc2UiLCJvdmVybGF5IjpmYWxzZX19

Note the + in the middle

![image](https://user-images.githubusercontent.com/2772505/147366853-ae36693e-a5d1-426b-9828-7f8dd832413b.png)

Pasting URL in the box then works.

Root cause: `getParameterByName` replaces `+` with space (utils.js#82)
```js
  decodeURIComponent(results[1].replace(/\+/g, " "));
```

**Comment by eddy-geek** [comment]
See PR.

By the way, I think getParameterByName could be replaced with the equivalent browser built-in:


```js
urlParams = new URLSearchParams(location.search);

function getParametersByName(name, defaultValue) {
  if (urlParams.has(name))
    return urlParams.get(name);
  return (isUnset(defaultValue) ? defaultValue : "")
}
```

**Comment by opoto** [comment]
Yes, I think getParameterByName should be replaced by:
```
urlParams = new URLSearchParams(location.search);
function getParameterByName(name, defaultValue) {
  return urlParams.get(name) || defaultValue
}
```

Keeping the function allows to minimize impact on the rest of the code. I can do this in Jan.
