### ISSUE TITLE
Ampersands in track name and/or description are not escaped in saved GPX

### ISSUE THREAD

**Issue by PikeUK** [opoto/wtracks#3]
Ampersands in the track name and/or the description are not escaped in the saved GPX file.

Steps to reproduce:
1. Click Edit track details pen icon.
2. Add an ampersand to name or description field then click OK.
3. Click menu->File->Save, save file.

The saved GPX file is invalid because the & is not escaped.

p.s. Thanks for the editor, great work.

**Comment by opoto** [comment]
Thanks again!
