### ISSUE TITLE
Make sequence of overlays configurable

### ISSUE THREAD

**Issue by Hufkratzer** [opoto/wtracks#44]
If I use several overlays together, the order of which overlay is drawn over which other seems to be somehow fixed. For example, if I use the Waymarked Trails overlays for cycling and hiking, the cycling routes are always drawn on the hiking routes. I changed the order of these overlays in the layer list (WTracks Maps Configuration), but that doesn't seem to affect the order in which the overlays are drawn. Can you make this configurable (e.g. depending on the sequence in the layer list)?

**Comment by opoto** [comment]
Hi
The overlays are displayed in the order they are listed in the map menu. The zIndex of each overlay, which defines the order in which overlays are displayed (the bigger is displayed on top), is automatically computed, and increases:

![image](https://user-images.githubusercontent.com/1472722/193459710-aaa68d2d-246c-456a-a4f8-67b23f0b4515.png)

However whatever transparency level you set, overlays always have "some" transparency (as least the one I tried), which makes it difficult to see which one is displayed on top.
If you find some evidence that my assumptions are wrong, please come back to me, with detailed example.
You can check in the browser console the zIndex of displayed layers with the following Javascript command:
`objectForEach(map._layers, function(lId, layer) {if (layer._url) console.log("layer ", layer._url," has zIndex", layer.options.zIndex)})`

**Comment by Hufkratzer** [comment]
It seems to me that the ways from a pmtiles overlay[^1] are always displayed on top of other ways/routes, and the command you gave above doesn't list any zIndex for this pmtiles overlay:
![wtracksoverlay](https://user-images.githubusercontent.com/5958184/193926287-ec5dc750-3355-4226-98d8-e853bc36cbcc.jpg)

Is this perhaps a pmtiles specific problem? The pmtiles file shows some ways around Dresden and was created with a python script[^2].

[^1]: https://opoto.github.io/wtracks/maps.html?import=eyJwbXRpbGVzIG92ZXJsYXkiOnsib3B0aW9ucyI6eyJtaW5ab29tIjo2LCJtYXhab29tIjoxNiwiYXR0cmlidXRpb24iOiJPU00ifSwidXJsIjoiaHR0cHM6Ly9lcmQuczMucGwtd2F3LnNjdy5jbG91ZC9yZWl0d2VnZS5wbXRpbGVzIiwidHlwZSI6InBtdGlsZXMiLCJvdmVybGF5Ijp0cnVlLCJuYW1lIjoiUmVpdHdlZ2UgRVJEIChPU00pIn19
[^2]: https://protomaps.com/docs/pmtiles/

**Comment by opoto** [comment]
The issue is actually related to the default "blending" mode of overlays that was configured in WTracks to smoothly combine multiple overlays, so that the upper one does not hide the others. I actually think this is offering a nice rendering, which I prefer compared to having the top overlay hiding (or greying is opacity is not 100%) the lower overlays.
To do some tests, I added a hiden option you can type in the browser console to deactivate this blending:
`localStorage.setItem("wt.noblend", true)`

Do you think it is better without blending?

You can restore default by typing:
`localStorage.removeItem("wt.noblend")`

**Comment by opoto** [comment]
I eventually added a Display option in Settings to switch between the 2 modes: "Do not combine overlays"
Default is still the previous rendering.

**Comment by Hufkratzer** [comment]
Thanks for the new option. I am now convinced that wtracks draws the overlays in the right order. I agree that the blending mode is generally more useful. Sorry for the inconvenience. (I didn't even know there was a blending mode before you pointed it out.)

**Comment by opoto** [comment]
No problem, at least now we have the choice !
