### ISSUE TITLE
Oh no! Outdoors map has disappeared :(

### ISSUE THREAD

**Issue by mudyc** [opoto/wtracks#8]
I use outdoors map quite frequently for finding trails.  Was there legal issues to remove the map tile?

**Comment by opoto** [comment]
Yes, sorry about that. I was using a free "Hobby Project" license, but considering the high traffic received from WTracks the Thunderforest team kindly asked me to either upgrade or stop using their maps. I cannot afford the monthly license cost, so I had to remove the map.
However if you want to use this map you can still buy a license on your own:
https://www.thunderforest.com/pricing/
And configure it at https://opoto.github.io/wtracks/maps.html by creating a new Map:

Name: Thunderforest Outdoor
Type: Base
URL: //{s}.tile.thunderforest.com/outdoors/{z}/{x}/{y}.png?apikey=<insert-your-apikey-here>
Zoom: 5 to 18
Copyright: &copy; <a href="https://www.thunderforest.com/">Thunderforest</a>, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>

**Comment by izaakvc** [comment]
Is this the same case for opencyclemap? It seems this has dissapeared as well...

**Comment by opoto** [comment]
Hello
Yes, this one was from ThunderForest too. URL is:
//{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=<insert-your-apikey-here>
